name: android_project_grp
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  sqflite: ^2.4.0  # Latest version
  http: ^1.2.2     # Latest version
  cupertino_icons: ^1.0.8  # Latest version
  firebase_core: ^3.6.0  # Latest version
  firebase_auth: ^5.3.1   # Latest version
  get: ^4.6.6
  shared_preferences: ^2.3.2  # Specified version
  socket_io_client: ^3.0.0  # Latest version
  web_socket_channel: ^3.0.1  # Latest version
  firebase_messaging: ^15.1.3  # Latest version
  flutter_local_notifications: ^17.2.3  # Latest version
  photo_view: ^0.15.0  # Latest version
  flutter_pdfview: ^1.3.3  # Latest version
  path_provider: ^2.1.4  # Latest version
  file_picker: ^8.1.3
  firebase_storage: ^12.3.4
  contacts_service: ^0.6.3
  cloud_firestore: ^5.4.4
  http_parser: ^4.0.0
  open_file: ^3.0.0
  url_launcher: ^6.1.10
  dio: ^5.0.0
  permission_handler: ^10.0.0
  flutter_native_contact_picker: ^0.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Latest version
  intl: ^0.19.0
flutter:
  assets:
    - assets/images/
    - android/app/google-services.json

  uses-material-design: true